# Generated by Django 4.1.7 on 2023-03-06 07:55

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_loginuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='user_pw',
            field=encrypted_fields.fields.EncryptedCharField(default=False, max_length=20),
        ),
    ]
