# Generated by Django 4.1.7 on 2023-03-06 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=False, max_length=20)),
                ('name', models.CharField(default='', max_length=256, verbose_name='작업이름')),
                ('start_date', models.DateField(default=datetime.datetime(2023, 3, 6, 10, 36, 13, 789712, tzinfo=datetime.timezone.utc), verbose_name='시작날짜')),
                ('end_date', models.DateField(null=True, verbose_name='마감날짜')),
                ('finish_date', models.DateField(null=True, verbose_name='완료날짜')),
                ('state', models.IntegerField(default=0, verbose_name='진행상태')),
            ],
            options={
                'verbose_name': 'todo_table',
                'db_table': 'task',
            },
        ),
    ]
